# Generated by Django 4.2 on 2026-03-23 19:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vip_level', models.IntegerField()),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_limit', models.IntegerField(default=1)),
                ('icon', models.CharField(default='bi-check-circle', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_profit_date', models.DateField(default=datetime.date.today)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VIPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_profit_percent', models.DecimalField(decimal_places=2, default=3.3, max_digits=5)),
                ('duration_days', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='VIPProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='vip.uservip')),
            ],
        ),
        migrations.AddField(
            model_name='uservip',
            name='vip_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.vipplan'),
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateField(default=datetime.date.today)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
