# Generated by Django 4.2 on 2026-03-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('CBE', 'CBE'), ('TeleBirr', 'Tele Birr')], default='CBE', max_length=50),
        ),
    ]
