# Generated by Django 4.2 on 2026-03-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_deposit_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='person_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
