# Generated by Django 4.2 on 2026-03-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_withdrawal_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='person_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('CBE', 'CBE'), ('TeleBirr', 'Tele Birr')], default='Telebirr', max_length=50),
        ),
    ]
