# Generated by Django 4.2 on 2026-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_deposit_person_name_alter_deposit_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('CBE', 'CBE'), ('TeleBirr', 'Tele Birr')], default='TeleBirr', max_length=50),
        ),
    ]
